# action name
name: 'build-linux-packages'

# action author
author: 'Kyle Penfound <kpenfound@hashicorp.com>'

# action description
description: 'Packages binaries using nfpm.'

# action input values
inputs:
  name:
    description: 'Product name.'
    default: ''
    required: true
  arch:
    description: 'Build architecture.'
    default: ''
    required: true
  version:
    description: 'Product semver version.'
    default: ''
    required: true
  maintainer:
    description: 'Maintainer name.'
    default: ''
    required: false
  description:
    description: 'Product description.'
    default: ''
    required: false
  homepage:
    description: 'Product homepage.'
    default: ''
    required: false
  license:
    description: 'Product license.'
    default: ''
    required: false
  binary:
    description: 'Binary location to package.'
    default: ''
    required: false
  config_dir:
    description: 'Directory of configs in desired filesystem structure.'
    default: ''
    required: false
  deb_depends:
    description: 'Comma separated list of deb dependencies.'
    default: ''
    required: false
  rpm_depends:
    description: 'Comma separated list of rpm dependencies.'
    default: ''
    required: false
  preinstall:
    description: 'Preinstall script location.'
    default: ''
    required: false
  postinstall:
    description: 'Postinstall script location.'
    default: ''
    required: false
  preremove:
    description: 'Preremove script location.'
    default: ''
    required: false
  postremove:
    description: 'Postremove script location.'
    default: ''
    required: false

# action runner (golang:latest image)
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GO111MODULE: 'on'
